// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_tEzWb6BTilRdbJLPTLbh4-9LgeaLr2Q',
    appId: '1:793692850186:web:e6015b252cfa8b1f4bf7f3',
    messagingSenderId: '793692850186',
    projectId: 'notification-2f0ef',
    authDomain: 'notification-2f0ef.firebaseapp.com',
    storageBucket: 'notification-2f0ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy-oH1cGVw4DoUUcXwU2o11d464R4wtr8',
    appId: '1:793692850186:android:88fc3082729967c94bf7f3',
    messagingSenderId: '793692850186',
    projectId: 'notification-2f0ef',
    storageBucket: 'notification-2f0ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd_IJyJ9PfPSJW22YHid_2s5lm0A9a9Dc',
    appId: '1:793692850186:ios:f8735c70890205b24bf7f3',
    messagingSenderId: '793692850186',
    projectId: 'notification-2f0ef',
    storageBucket: 'notification-2f0ef.firebasestorage.app',
    iosBundleId: 'com.example.vchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd_IJyJ9PfPSJW22YHid_2s5lm0A9a9Dc',
    appId: '1:793692850186:ios:f8735c70890205b24bf7f3',
    messagingSenderId: '793692850186',
    projectId: 'notification-2f0ef',
    storageBucket: 'notification-2f0ef.firebasestorage.app',
    iosBundleId: 'com.example.vchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_tEzWb6BTilRdbJLPTLbh4-9LgeaLr2Q',
    appId: '1:793692850186:web:8b773db180b530394bf7f3',
    messagingSenderId: '793692850186',
    projectId: 'notification-2f0ef',
    authDomain: 'notification-2f0ef.firebaseapp.com',
    storageBucket: 'notification-2f0ef.firebasestorage.app',
  );
}
